image: python:latest

variables:
    POSTGRES_DB: $database_name
    POSTGRES_PASSWORD: $POSTGRES_PW
    POSTGRES_USER: $POSTGRES_USR

default:
    services:
        - postgres:latest

    cache:
        paths:
            - ~/.cache/pip/

    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - apt-get install -y apt-utils
        - apt-get install -y net-tools python3 python3-pip
        - apt-get -y upgrade
        - pip3 install -r requirements.txt

# 4 stages
stages:
    - build

migrations:
    stage: build
    script:
        - python3 manage.py makemigrations
        - python3 manage.py migrate
        - python3 manage check


# # 4th job STAGING DEPLOY (on Heroku)
# fo-deploy-staging:
#     stage: deploy
#     image: ruby:latest
#     script:
#         - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
#     only:
#         - Api
