image: node:latest

# Must Use for Heroku deploy
before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - apt-get install -y apt-utils
    - apt-get install -y net-tools python3 python3-pip
    - apt-get -y upgrade
    - pip3 install -r diagPlus/requirements.txt
  
# 4 stages
stages:
    - install
    - test
    - deploy

# 4th job STAGING DEPLOY (on Heroku)
fo-deploy-staging:
    stage: deploy
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - Api