# Generated by Django 4.0 on 2022-07-25 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(default=160, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(default='Origin', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Patient', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(default=70, max_length=50),
        ),
    ]
