# Generated by Django 4.0 on 2022-01-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Speciality')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
                ('practicien_speciality', models.CharField(max_length=255, verbose_name='Practicien Speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('domain', models.PositiveIntegerField(verbose_name='Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Speciality')),
                ('definition', models.CharField(max_length=255, verbose_name='Defintion')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Speciality')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
                ('pathologies', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.pathologies')),
            ],
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Speciality')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
                ('pathologies', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.pathologies')),
            ],
        ),
        migrations.AddField(
            model_name='pathologies',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.speciality'),
        ),
    ]
