# Generated by Django 4.0 on 2022-01-14 16:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_pathologies_questions_speciality_remove_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.PositiveIntegerField(verbose_name='Type')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('pathology_bot', models.PositiveIntegerField()),
                ('pathology_practicien', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zipcode')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('smoker', models.BooleanField(verbose_name='Smoker')),
                ('is_drinker', models.BooleanField(verbose_name='Drinker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Response')),
                ('diagnostic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.diagnostic')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.questions')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('contenu', models.CharField(max_length=255, verbose_name='Content')),
                ('attachment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.attachments')),
                ('patients', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Praticiens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zipcode')),
                ('speciality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.speciality')),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('start_hours', models.DateTimeField()),
                ('end_hours', models.DateTimeField()),
                ('practiciens', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.praticiens')),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(max_length=255, verbose_name='Antecedent')),
                ('allergy', models.CharField(max_length=255, verbose_name='Allergy')),
                ('important_act', models.CharField(max_length=255, verbose_name='Important Act')),
                ('organ_donation', models.CharField(max_length=255, verbose_name='Organ Donation')),
                ('previous_medication', models.CharField(max_length=255, verbose_name='Previous Medication')),
                ('current_medication', models.CharField(max_length=255, verbose_name='Current Medication')),
                ('patients', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.patients')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.patients'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='practiciens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.praticiens'),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('reason', models.TextField(verbose_name='Reason')),
                ('physical', models.BooleanField(verbose_name='Physical')),
                ('patients', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.patients')),
                ('practiciens', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.praticiens')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
    ]
