# Generated by Django 4.0 on 2022-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name'),
        ),
    ]
