# Generated by Django 4.0 on 2022-01-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_attachments_diagnostic_patients_user_permission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Praticiens',
            new_name='Praticien',
        ),
        migrations.RenameModel(
            old_name='ReportPatients',
            new_name='ReportPatient',
        ),
    ]
