# Generated by Django 4.0 on 2022-01-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_rename_admins_admin_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='Pathologies',
            new_name='Pathology',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Reasons',
            new_name='Reason',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
    ]
