# Generated by Django 4.0 on 2022-07-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_user_address_user_city_user_telephone_user_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
