# Generated by Django 4.0 on 2022-07-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
    ]
