# Generated by Django 4.0 on 2022-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_patient_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='users',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='users',
        ),
        migrations.RemoveField(
            model_name='praticien',
            name='users',
        ),
    ]
