# Generated by Django 4.0 on 2022-07-25 10:05

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Api', '0007_remove_admin_users_remove_patient_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(default='Address', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.CharField(default='City', max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='admin',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='alexandreto1996@gmail.com', max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='permission',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='admin',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='admin',
            name='zipcode',
            field=models.CharField(default='00000', max_length=5, verbose_name='Zipcode'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='aex', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='email',
            field=models.EmailField(default='test', max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='praticien',
            name='password',
            field=models.CharField(default='test', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
