# Generated by Django 4.0 on 2022-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_admin_email_alter_speciality_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=50, verbose_name='Gender'),
        ),
    ]
