# Generated by Django 4.0 on 2022-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='birth_date',
            field=models.DateField(default='2022-07-21',
                                   verbose_name='Birth Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='gender',
            field=models.CharField(
                default='Male', max_length=50, verbose_name='Gender'),
        ),
    ]
